services:
  - type: web
    name: foodcartfinder
    env: node
    buildCommand: |
      npm install
      cd client && npm install && npm run build && cd ..
      mkdir -p /opt/render/project/src/client/build
      cp -r client/build/* /opt/render/project/src/client/build/
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
    buildFilter:
      paths:
      - client/**
      - server.js
      - package.json
      - routes/** 