services:
  - type: web
    name: foodcartfinder
    env: node
    buildCommand: |
      echo "Installing dependencies..."
      npm install
      echo "Building client application..."
      cd client && npm install && npm run build
      echo "Build complete. Contents of client/build:"
      ls -la client/build
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromDatabase:
          name: foodcartfinder-db
          property: uri
      - key: JWT_SECRET
        generateValue: true
      - key: REACT_APP_API_URL
        value: /api
    healthCheckPath: /api/health
    autoDeploy: true
    buildFilter:
      paths:
      - client/**
      - server.js
      - package.json
      - routes/**
      - config/**
      - models/**
      - .env
      - .env.production 