services:
  - type: web
    name: foodcartfinder
    env: node
    buildCommand: |
      echo "Step 1: Installing root dependencies..."
      npm install
      
      echo "Step 2: Installing client dependencies..."
      cd client
      npm install --legacy-peer-deps
      
      echo "Step 3: Building client application..."
      npm run build
      
      echo "Step 4: Moving back to root..."
      cd ..
      
      echo "Step 5: Creating build directory..."
      mkdir -p /opt/render/project/src/client/build
      
      echo "Step 6: Copying build files..."
      cp -r client/build/* /opt/render/project/src/client/build/
      
      echo "Step 7: Verifying build directory..."
      ls -la /opt/render/project/src/client/build/
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
    buildFilter:
      paths:
      - client/**
      - server.js
      - package.json
      - routes/** 